version: '3.8'

services:
  forehouse-mongodb:
    image: mongo:latest
    container_name: forehouse-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongodb_data:/districts/db

volumes:
  mongodb_data:
